### ISSUE TITLE
Add .gitignore please

### ISSUE THREAD

**Issue by playday3008** [Finguimbrine/CSGO-Cheat-Loader3#1]
https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

**Comment by Finguimbrine** [comment]
Why wtf

**Comment by playday3008** [comment]
If someone fork your repo and he forgot add gitignore, he can commit to repo temporary files and "Release" or "Debug" folder

**Comment by playday3008** [comment]
And update api here

**Comment by Finguimbrine** [comment]
updated the api
