### ISSUE TITLE
I have error in injection moment

### ISSUE THREAD

**Issue by rose1337** [Finguimbrine/CSGO-Cheat-Loader3#2]
https://i.imgur.com/1RSoopk.png
I have this, when trying to inject, my link looks fine, like this: http://1231232132.pw/test_encrypted.dll

help me please

**Comment by Finguimbrine** [comment]
your vars have not been setup correctly, 
![image](https://user-images.githubusercontent.com/50637180/80258740-546f9980-865a-11ea-88e2-c3dca62bee41.png)
