### ISSUE TITLE
problem with injection

### ISSUE THREAD

**Issue by rose1337** [Finguimbrine/CSGO-Cheat-Loader3#3]
https://i.imgur.com/1RSoopk.png
I have this, when trying to inject, my link looks fine, like this: http://1231232132.pw/test_encrypted.dll

help me please

This writing me "invalid_var", not found, what var?

`mac.Headers.Add("User-Agent", c_api.c_var("Mozilla FireFrame")); 

byte[] crypted = mac.DownloadData(c_api.c_var("https:/test.pw/1_encrypted.dll")); 
                    byte[]decrypted=AES.DecryptAES(crypted,Encoding.UTF8.GetBytes(c_api.c_var("XSaBw6JkWFZh7PBgLQb5TndqzEkm")));

my current vars

**Comment by Finguimbrine** [comment]
you didnt understand the concept of the vars, they are meant to be used like a "identifier" to the original link, go to your firefra.me var panel, add vars with the name like, "download" and put the real link there. The same with the crypt_pass var and all, the reason im using vars is to not use links directly

**Comment by rose1337** [comment]
oh man, thank you, i'm retarded

**Comment by rose1337** [comment]
can u make in next your loader, firefra.me with x64 injection? i be very grateful for this :*

**Comment by rose1337** [comment]
Waiting for ur answer on my last question)

**Comment by Finguimbrine** [comment]
I could, just link me an x64 injection

**Comment by rose1337** [comment]
https://www.unknowncheats.me/forum/general-programming-and-reversing/209939-alisaalis-manual-map-dll-injector-x86-x64.html

x64/x86 c++ injector

https://github.com/Reloaded-Project/Reloaded.Injector = c# injector x86/x64, waiting for ur amazing work with firefram.me)

**Comment by rose1337** [comment]
If u can, add me in discord Rose#9983

**Comment by Finguimbrine** [comment]
well used another one, but im not really sure if everything is working fine, please do the test for me
